# Generated by Django 4.2.4 on 2023-08-20 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_delete_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Student'},
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
